[versions]
hubdle = "0.2.0-alpha.46"

[libraries]
javiersc-semver-core = "com.javiersc.semver:semver-core:0.1.0-beta.12"

[plugins]
javiersc-hubdle = { id = "com.javiersc.hubdle", version.ref = "hubdle" }
