[versions]
hubdle = "0.5.0-alpha.12"

[libraries]
javiersc-semver-core = "com.javiersc.semver:semver-core:0.1.0-beta.13"

[plugins]
javiersc-hubdle = { id = "com.javiersc.hubdle", version.ref = "hubdle" }
